### PR TITLE
implemented filter functionality + small fixes

### LINKED ISSUE #241: Implement filters on "Pre-Sale Wines"-Page
This task involves backend for the filters on the pre-sale wines. Another task will focus on the frontend.

### Steps
1. Gather the different options from these fields in Figma (wine type, grape, region, price)
2. Dynamically create clickable checkboxes with these options for each filter-dropdown
3. Implement filter logic to filter which wines are seen in the pre-sale wines grid

### Preview from Figma
Image

### PR DESCRIPTION
**Pull request by AnastasiaSkachenko**
# Pull Request Title

[FEATURE] Implement Pre-Sale Filters Functionality + Small Fixes

## Description

This PR implements the functionality for the four filters on the pre-sale page, so that users can filter wines as expected. I also fixed some small layout problems, but found one layout issue (spinner position) that I did not fix yet, as it may depend on further layout decisions.

- What problem does this PR solve? Previously we had just UI for filters, now everything works and behaves expected way. 
- What is the impact of the change? Basic functionality for filters is implemented and we can start working on search and sortBy functionalities.

## Changes Made

List the main changes in this pull request. Describe what was added, modified, or removed.

- **UI Components:** Updated FilterDropdown and ModalFilterDropdown to actually apply filters. Minor adjustments to the page grid to prevent it from overflowing into the footer. 
- **State Management:** In PreSaleContext, implemented filtering logic so page.js only displays filtered wines. Added activeFilters state, memoized wines, added allWines to store full fetched data, and introduced availableFilters to reflect only current stock.
- **Styling:** Minor CSS updates to prevent grid overflow. Spinner alignment issue noted but not fixed yet.

## Screenshots (if applicable)

Here is the issue I was talking about. The spinner is currently positioned too far to the right. I decided not to fix it in this PR, since further layout work is expected on the pre-sale page. Flagging it here so it’s not overlooked.

Screenshot 2025-07-12 at 18 34 07

## Testing Steps

Explain how reviewers can test this PR locally.

1. **Setup:** Use deployment link. On mobile screen filters scroll is yet to be implemented. To test how price filter works in modal: open devTools and delete top-[14rem] class so you will be able to see full content for modal. 
2. **Steps:**
 

- [ ] Go to /pre-sale
- [ ]  Apply different filters and verify they apply correctly
- [ ] Test the same on mobile
- [ ] Resize the screen and toggle modal to ensure filter state persists

4. **Expected Result:** Filters should directly update list of wines without any delays.

## Issues Addressed
 
Closes #241

### CODE REVIEW

File: src/utils/wineUtils.js [hunk 1]
```diff
@@ -86,3 +86,61 @@ export const getWineBySlug = (slug, wines) => {
 
 // this utility function generates a URL for a wine based on its slug
 export const getWineUrl = (wine) => `/wines/pre-sale/${wine.slug}`;
+
```
Comment (SimonFromSweden) [inline src/utils/wineUtils.js:89]: I really like this extractFilters-function, nice setup

**Review by SimonFromSweden — APPROVED** [review]
This PR works flawlessl. I like how the code is structured in a very clean, well-thought out way. Great work!
